---
- name: 웹서버 설치
  hosts: all 
  become: yes
  
  tasks:
    - name: Create Nginx Service
      docker_swarm_service:
        name: nginx_service
        image: nginx
        replicas: 3
        publish: "8888:80"
        state: present
