---
- name: nginx 배포하기
  hosts: localhost
  become: no
  
  tasks:
    - name: nginx
      command: docker service create mynginx --replicas 3 --constraint node.role==worker --with-registry-auth -p 8008:80 nginx 
