---
- name: awxtest
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Create Docker service
      docker_swarm_service:
        name: test1
        state: present
        replicas: 3
        placement:
          constraints:
            - "node.role==worker"
        args: "--with-registry-auth -p 8001:80"
        image: "nginx:latest"
